---
- name: Install Docker, Docker-Compose, and NGINX
  hosts: all
  become: yes
  
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies for Docker and NGINX
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - nginx
        state: present

    # Docker Installation Steps
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: latest

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Docker Compose Installation
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version

    - name: Print Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"

    # NGINX Installation and Configuration
    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Print NGINX status
      command: systemctl status nginx
      register: nginx_status

    - name: Display NGINX status
      debug:
        msg: "{{ nginx_status.stdout_lines }}"
